#!/usr/bin/env bash
# Quick Start: Analysis Tools
# Copy this into your terminal to get started

echo "🚀 SCIoT Analysis Tools - Quick Start"
echo ""
echo "Step 1: Run Simulations (15 minutes)"
echo "  python simulation_runner.py"
echo ""
echo "Step 2: Find Results Folder"
echo "  ls -d simulated_results/simulation_*/ | sort -r | head -1"
echo ""
echo "Step 3: Analyze Results (10 seconds)"
echo "  python analyze_simulation.py simulated_results/simulation_YYYYMMDD_HHMMSS/"
echo ""
echo "Step 4: View Results"
echo "  open simulated_results/simulation_YYYYMMDD_HHMMSS/analysis/"
echo ""
echo "Step 5 (Optional): Run Custom Analysis"
echo "  python example_analysis.py"
echo ""
echo "📊 Generated Plots:"
echo "  ✓ 01_device_vs_edge_time.png"
echo "  ✓ 02_total_inference_time.png"
echo "  ✓ 03_throughput_comparison.png"
echo "  ✓ 04_timing_distributions.png"
echo "  ✓ 05_layer_statistics.png"
echo "  ✓ 06_scenario_comparison_dashboard.png (MAIN PLOT)"
echo "  ✓ 07_summary_statistics.png"
echo "  ✓ summary_statistics.csv"
echo ""
echo "📖 Documentation:"
echo "  • SIMULATION_RUNNER_README.md  - How to run simulations"
echo "  • ANALYSIS_README.md           - How to use analysis tool"
echo "  • SIMULATION_ANALYSIS_GUIDE.md - Interpret plots and results"
echo "  • TOOLS_SUMMARY.md             - Complete reference"
echo "  • example_analysis.py          - 10 runnable examples"
echo ""
echo "⚡ One-liner to run everything:"
echo "  python simulation_runner.py && LATEST=\$(ls -d simulated_results/simulation_*/ | sort -r | head -1) && python analyze_simulation.py \$LATEST && open \$LATEST/analysis/"
echo ""
